# app/services/pdf_upload_service.py

from app.services.document_service import process_pdf
from app.services.embedding_service import get_embeddings
from app.db.vector_setup import create_collection
from app.db.mongo import db
from datetime import datetime


async def upload_and_process_pdf(
    file_path: str,
    user_id: str,
    book_id: str,
    title: str
) -> dict:
    """
    Upload PDF, process with LangChain, embed, and store in Milvus + MongoDB
    """

    try:
        # 1. Load and split PDF using LangChain
        print(f"📖 Processing PDF: {title}")

        documents = process_pdf(file_path)

        if not documents:
            return {
                "success": False,
                "error": "No content extracted from PDF"
            }

        # 2. Prepare chunks
        chunks_to_process = []

        for doc in documents:
            chunks_to_process.append({
                "content": doc.page_content,
                "page_number": doc.metadata.get("page", 0),
                "metadata": doc.metadata
            })

        # 3. Generate embeddings
        print(f"⚙️ Embedding {len(chunks_to_process)} chunks...")

        chunk_contents = [c["content"] for c in chunks_to_process]

        embeddings_list = get_embeddings(chunk_contents)

        # 4. Prepare Milvus insert data
        collection = create_collection()

        milvus_data = []

        for chunk_info, embedding in zip(chunks_to_process, embeddings_list):
            milvus_data.append({
                "user_id": user_id,
                "book_id": book_id,
                "embedding": embedding
            })

        # 5. Insert into Milvus
        print(f"📊 Inserting {len(milvus_data)} chunks into Milvus...")

        insert_result = collection.insert(milvus_data)

        collection.flush()

        # REAL Milvus IDs generated by auto_id=True
        milvus_ids = insert_result.primary_keys

        # 6. Prepare MongoDB documents using REAL Milvus IDs
        mongo_chunks = []

        for idx, chunk_info in enumerate(chunks_to_process):

            mongo_chunk = {
                "milvus_id": str(milvus_ids[idx]),
                "user_id": user_id,
                "book_id": book_id,
                "chunk": chunk_info["content"],
                "page_number": chunk_info["page_number"],
                "created_at": datetime.utcnow()
            }

            mongo_chunks.append(mongo_chunk)

        # 7. Insert chunks into MongoDB
        print(f"💾 Storing {len(mongo_chunks)} chunks in MongoDB...")

        if mongo_chunks:
            await db.chunks.insert_many(mongo_chunks)

        # 8. Update book metadata
        await db.books.update_one(
            {"_id": book_id} if isinstance(book_id, str) else {"_id": book_id},
            {
                "$set": {
                    "has_pdf": True,
                    "chunks_count": len(documents)
                }
            }
        )

        print(f"✅ Successfully processed and stored {len(documents)} chunks")

        return {
            "success": True,
            "chunks_created": len(documents),
            "book_id": book_id,
            "message": f"PDF processed successfully with {len(documents)} chunks"
        }

    except Exception as e:
        print(f"❌ PDF Upload Error: {str(e)}")
        raise e